version: '3.8'

services:
  db:
    image: postgres:16.3-alpine
    restart: always
    environment:
      POSTGRES_USER: NewsDailyUser
      POSTGRES_PASSWORD: NewsDailyPassword
      POSTGRES_DB: NewsDailyDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: